server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: someuser
    password: somepass
num.handle: 3